initial_commit
devs-jequie/site-backend pull request #1
Opened 2022-09-30 15:39 UTC by laianribas

2022-09-30 17:00 UTC, tuliocll requested changes

2022-09-30 17:00 UTC, tuliocll commented on app/Controllers/Http/AuthController.ts
> +    // Lookup user manually
pode remover esses comentarios

2022-09-30 17:00 UTC, tuliocll commented on app/Controllers/Http/AuthController.ts
> +    const email = request.input('email')
talvez verificar se o email e senha existe, antes de usar, ou criar um validator seja legal tbm

2022-09-30 17:00 UTC, tuliocll commented on start/routes.ts
> +})
corrige esse espaço aqui

2022-09-30 17:43 UTC, philipep-galdino commented on app/Controllers/Http/AuthController.ts
> +    const email = request.input('email')
a ideia é maneira. dá pra por enqnt deixar verificando se existe antes de usar, só, e dps seguir com um validator pra campos e tal

2022-10-01 14:46 UTC, tuliocll approved these changes

2022-10-01 14:46 UTC, merged